Updated merge script

diff --git a/scripts/merge_upstream b/scripts/merge_upstream
--- a/scripts/merge_upstream
+++ b/scripts/merge_upstream
@@ -73,6 +73,17 @@ if ! git tag -d ${TAG}  &> /dev/null; then
     exit 1
 fi
 
+echo "Setting version in snapcraft.yaml"
+if ! sed "s/VERSION/${TAG}/g" snap/snapcraft.yaml.template > snap/snapcraft.yaml; then
+    echo "Could not set version of snapraft.yaml"
+    exit 1
+fi
+
+if ! git commit snap/snapcraft.yaml -m "Settng version ${TAG} in snapcraft.yaml"; then
+    echo "Could not commit snapcraft.yaml"
+    exit 1
+fi
+
 echo "Adding local tag ${TAG} to HEAD"
 if ! git tag -a ${TAG} -m "Added tag ${TAG}" &> /dev/null; then
     echo "Could not add local tag ${TAG} to HEAD"
